export const SET_SNACKBAR = 'SET_SNACKBAR';

export const SET_TEMA_APP = 'SET_TEMA_APP';

export const SET_COR_TEMA = 'SET_COR_TEMA';

export const SET_MODO_TEMA = 'SET_MODO_TEMA';

export const SET_PRIMARY_DRAWER = 'SET_PRIMARY_DRAWER';

export const SET_PRIMARY_DRAWER_STATUS = 'SET_PRIMARY_DRAWER_STATUS';

export const SET_SECONDARY_DRAWER = 'SET_SECONDARY_DRAWER';

export const SET_SECONDARY_DRAWER_STATUS = 'SET_SECONDARY_DRAWER_STATUS';

export const SET_THEME_DRAWER = 'SET_THEME_DRAWER';
